import os

ATALANTA_HOME = "third_party/Atalanta"
ATALANTA_BIN = f"{ATALANTA_HOME}/atalanta"
STAGING_DIR = "staging/"
CIRCUIT_FILE = f"{STAGING_DIR}circuit.bench"
FAULT_FILE = f"{STAGING_DIR}f.fault"
PATTERN_FILE = f"{STAGING_DIR}pattern.txt"
ATALANTA_ARGS = "-b 1000"

SKIP_LINES = 9  # Number of lines to skip in the output file


def cleanup():
    """Cleanup staging directory."""
    import os
    import shutil

    if os.path.exists(STAGING_DIR):
        shutil.rmtree(STAGING_DIR)

    os.makedirs(STAGING_DIR, exist_ok=True)  # Recreate staging directory


def copy_bench(file_path):
    """Copy a .bench file to the staging directory."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Benchmark file {file_path} does not exist.")

    cleanup()  # Ensure staging directory is clean

    lines = []
    with open(file_path, "r") as f:
        lines = f.readlines()

    with open(CIRCUIT_FILE, "w") as f:
        # Write a comment line to avoid Atalanta issues
        f.write("# Benchmark file generated by Atalanta integration\n\n")
        for line in lines:
            f.write(line)


def write_bench(nodes, edges):
    """Write the graph to a .bench file."""
    cleanup()  # Ensure staging directory is clean

    nodes = dict(nodes)  # Ensure nodes is a dictionary
    edges = list(edges)  # Ensure edges is a list of tuples

    bench_file = CIRCUIT_FILE
    with open(bench_file, "w") as f:
        f.write(
            "# Benchmark file generated by Atalanta integration\n\n"
        )  # Atalanta goes crazy if the first line is not a comment

        # Write INPUT declarations
        input_nodes = [
            node_id for node_id, attrs in nodes.items() if attrs.get("type") == "INPUT"
        ]
        for node_id in sorted(input_nodes, key=int):
            f.write(f"INPUT({node_id})\n")

        f.write("\n")

        # Write OUTPUT declarations
        output_nodes = [
            node_id for node_id, attrs in nodes.items() if attrs.get("is_output", False)
        ]
        for node_id in sorted(output_nodes, key=int):
            f.write(f"OUTPUT({node_id})\n")

        f.write("\n")

        # Build input mapping for each gate
        gate_inputs = {}
        for source, target in edges:
            if target not in gate_inputs:
                gate_inputs[target] = []
            gate_inputs[target].append(source)

        # Write gate definitions
        gate_nodes = [
            node_id for node_id, attrs in nodes.items() if attrs.get("type") != "INPUT"
        ]
        for node_id in sorted(gate_nodes, key=int):
            attrs = nodes[node_id]
            gate_type = attrs.get("type", "NAND")
            inputs = sorted(gate_inputs.get(node_id, []), key=int)

            if inputs:
                inputs_str = ", ".join(inputs)
                f.write(f"{node_id} = {gate_type}({inputs_str})\n")
            else:
                # Handle gates with no inputs (shouldn't happen in normal circuits)
                f.write(f"{node_id} = {gate_type}()\n")

        f.write("\n")

    return bench_file


def write_fault_file(fault):
    """Write the fault to a .fault file."""
    with open(FAULT_FILE, "w") as f:
        f.write(f"{fault}\n")


def run_atalanta():
    """Run the Atalanta tool."""
    import subprocess
    import time

    # Generate exactly one pattern per fault with very large backtrack limits.
    # Notes:
    # -D 1 : derive exactly one test pattern per fault (diagnostic mode)
    # -b/-B: large caps for phase-1 and phase-2 backtracks
    # -r 0 : disable random pattern testing
    # -N   : disable pattern compaction
    # -f/-t: fault list input and pattern output
    cmd = [
        f"{ATALANTA_BIN}",
        "-D",
        "1",
        "-b",
        "1000000",
        "-r",
        "0",
        "-N",
        "-f",
        FAULT_FILE,
        "-t",
        PATTERN_FILE,
        CIRCUIT_FILE,
    ]

    start_time = time.time()
    subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    end_time = time.time()
    return end_time - start_time


def read_output():
    """Read the output file generated by Atalanta."""
    output_file = PATTERN_FILE
    patterns = []
    if not os.path.exists(output_file):
        raise FileNotFoundError(f"Output file {output_file} does not exist.")

    with open(output_file, "r") as f:
        # Skip the first SKIP_LINES and filter out empty lines
        lines = f.readlines()[SKIP_LINES:]
        non_empty_lines = [line.strip() for line in lines if line.strip()]

    # Extract patterns from the remaining lines
    for line in non_empty_lines:
        try:
            # Check if line contains a colon (required for Atalanta format)
            if ":" in line:
                # Split by colon and take the part after it
                parts = line.split(":", 1)
                if len(parts) > 1:
                    # Get the pattern part (after colon) and split by whitespace
                    pattern_part = parts[1].strip()
                    if pattern_part:
                        # Take the first word after the colon as the pattern
                        pattern = pattern_part.split()[0]
                        if pattern:  # Only add non-empty patterns
                            patterns.append(pattern)
        except (IndexError, ValueError) as _:
            # Skip malformed lines and continue
            continue

    return patterns
