"""PyTorch Dataset for reconvergent path pairs with embeddings.

This module provides a Dataset class compatible with the training pipeline in
train_reconv.py. It loads reconvergent path pairs generated by reconv_podem.py
and prepares them for training the Multi-Path transformer model.
"""

from __future__ import annotations

import os
import pickle
from typing import Dict, Any, List, Optional, Tuple
from functools import lru_cache

import torch
from torch.utils.data import Dataset
from src.util.io import parse_bench_file
from src.util.struct import GateType


class ReconvergentPathsDataset(Dataset):
    """Dataset for reconvergent path pairs with structural embeddings.
    
    Each sample contains:
    - paths_emb: [P, L, D] tensor of node embeddings along P paths of length L
    - attn_mask: [P, L] boolean mask indicating valid positions
    - node_ids: [P, L] tensor of node IDs for constraint checking
    - file: string path to the circuit file
    
    Parameters
    ----------
    dataset_path : str
        Path to the pickle file containing the dataset.
    device : torch.device
        Device to place tensors on (cpu or cuda).
    prefer_value : int
        Preferred value for initialization (unused in current implementation).
    max_path_length : int
        Maximum path length to pad/truncate to.
    """
    
    def __init__(
        self,
        dataset_path: str,
        device: torch.device = torch.device('cpu'),
        prefer_value: int = 1,
        max_path_length: int = 50,
        # Optional fast path: use preprocessed on-disk shards with tensors
        processed_dir: Optional[str] = None,
        load_processed: bool = False,
        add_logic_value: bool = True,
        anchor_in_dataset: bool = False,
        max_len_filter: int = 0,
    ):
        self.dataset_path = dataset_path
        self.device = device
        self.prefer_value = prefer_value
        self.max_path_length = max_path_length
        self.processed_dir = processed_dir
        self.load_processed = load_processed
        self.add_logic_value = add_logic_value
        self.anchor_in_dataset = anchor_in_dataset
        self.max_len_filter = max_len_filter
        self._prefer_value = int(prefer_value)
        
        # Disable processed mode if filtering is active (for simplicity)
        if self.max_len_filter > 0 and self.load_processed:
            print(f"Disabling load_processed because max_len_filter={self.max_len_filter} is active.")
            self.load_processed = False
        
        # If using processed mode and cache exists, set up shard index and return
        self._shard_files: List[str] = []
        self._shard_sizes: List[int] = []
        self._current_shard_id: Optional[int] = None
        self._current_shard: Optional[Dict[str, Any]] = None

        if self.load_processed and self.processed_dir and os.path.isdir(self.processed_dir):
            shard_paths = sorted(
                [os.path.join(self.processed_dir, f) for f in os.listdir(self.processed_dir) if f.startswith('shard_') and f.endswith('.pt')]
            )
            if shard_paths:
                # Lightweight probe to get sizes without loading all tensors
                for sp in shard_paths:
                    meta = torch.load(sp, map_location='cpu')
                    n = int(meta['paths_emb'].shape[0])
                    self._shard_files.append(sp)
                    self._shard_sizes.append(n)
                self._use_processed = True
                self._total_len = sum(self._shard_sizes)
                print(f"Loaded processed shards from {self.processed_dir} ({len(self._shard_files)} shards, {self._total_len} samples)")
            else:
                self._use_processed = False
        else:
            self._use_processed = False

        # Fallback: load raw pickle dataset
        if not getattr(self, '_use_processed', False):
            with open(dataset_path, 'rb') as f:
                self.data = pickle.load(f)
            # Check if dataset has embeddings
            if len(self.data) > 0:
                sample = self.data[0]
                if 'struct_emb' not in sample or 'gate_mapping' not in sample:
                    print(f"[WARNING] Dataset at {dataset_path} is in old format without embeddings.")
                    print("[WARNING] Using random dummy embeddings. Consider rebuilding with:")
                    print("[WARNING]   python -m src.atpg.reconv_podem")
            
            # Apply max_len filtering
            if self.max_len_filter > 0:
                original_len = len(self.data)
                # self.data is a list of dicts. Keys: 'paths', 'paths_emb', etc.
                # path structure: list of lists of nodes.
                # We filter by checking if ANY path in the sample exceeds max_len_filter?
                # Or if ALL paths are short enough? 
                # Let's say: we want training samples where the reasoning chain is short. 
                # So we filter out samples where the path length > max_len_filter.
                # Assuming all paths in a sample have roughly same effective length if padded, 
                # but 'paths' key has the actual lists.
                new_data = []
                for sample in self.data:
                    # Check length of the first path (they are reconvergent, so approx same depth)
                    # sample['info']['paths'] is [[nid, nid, ...], ...]
                    if 'info' in sample and 'paths' in sample['info']:
                        p_lens = [len(p) for p in sample['info']['paths']]
                        if max(p_lens) <= self.max_len_filter:
                            new_data.append(sample)
                self.data = new_data
                print(f"Filtered dataset by max_len={self.max_len_filter}: {original_len} -> {len(self.data)} samples")
                
            print(f"Loaded {len(self.data)} samples from {dataset_path}")

    @staticmethod
    @lru_cache(maxsize=128)
    def _load_circuit_cached(bench_file: str):
        circuit, _ = parse_bench_file(bench_file)
        return circuit

    @staticmethod
    def _compatible_anchor_value(gate_type: int, prefer_value: int) -> int:
        # Heuristic mapping (non-controlling bias)
        if gate_type == GateType.AND or gate_type == GateType.NAND:
            return 1
        if gate_type == GateType.OR or gate_type == GateType.NOR:
            return 0
        return int(prefer_value)

    def _gen_anchor_for_sample(self, node_ids: torch.Tensor, attn_mask: torch.Tensor, file_path: str) -> Tuple[int, int, int]:
        """Pick a random path that has any valid nodes, take its last node,
        and compute a compatible anchor value. Returns (p, l, v) or (-1,-1,0)."""
        P, L = node_ids.shape[:2]
        candidates: List[Tuple[int, int, int]] = []  # (p, last_idx, gate_type)
        circuit = self._load_circuit_cached(file_path)
        for p in range(P):
            valid_positions = attn_mask[p]
            if bool(valid_positions.any()):
                last_idx = int(valid_positions.sum().item()) - 1
                cur_id = int(node_ids[p, last_idx].item())
                if cur_id > 0:
                    gty = int(circuit[cur_id].type)
                    candidates.append((p, last_idx, gty))
        if not candidates:
            return -1, -1, 0
        pick = torch.randint(low=0, high=len(candidates), size=(1,)).item()
        p_sel, l_sel, g_sel = candidates[int(pick)]
        v_sel = self._compatible_anchor_value(g_sel, self._prefer_value)
        return int(p_sel), int(l_sel), int(v_sel)
    
    def __len__(self) -> int:
        if getattr(self, '_use_processed', False):
            return self._total_len
        return len(self.data)
    
    def __getitem__(self, idx: int) -> Dict[str, Any]:
        """Get a single dataset item.
        
        Returns
        -------
        dict
            Dictionary with keys:
            - paths_emb: [P, L, D] embeddings for each node in each path
            - attn_mask: [P, L] boolean mask (True = valid position)
            - node_ids: [P, L] node IDs for each position
            - file: circuit file path
        """
        # Fast path: load from preprocessed shards
        if getattr(self, '_use_processed', False):
            shard_id, local_idx = self._locate_shard(idx)
            self._ensure_shard_loaded(shard_id)
            assert self._current_shard is not None
            paths_emb = self._current_shard['paths_emb'][local_idx].to(torch.float32).to(self.device)
            attn_mask = self._current_shard['attn_mask'][local_idx].to(self.device)
            node_ids = self._current_shard['node_ids'][local_idx].to(self.device)
            file_path = self._current_shard['files'][local_idx]
            # Optionally integrate anchor hint at dataset level
            if self.anchor_in_dataset:
                p_sel, l_sel, v_sel = self._gen_anchor_for_sample(node_ids, attn_mask, file_path)
                if p_sel >= 0 and l_sel >= 0 and self.add_logic_value and paths_emb.shape[-1] >= 3:
                    D = paths_emb.shape[-1]
                    onehot = torch.tensor([1.0, 0.0, 0.0], device=self.device)
                    if v_sel == 1:
                        onehot = torch.tensor([0.0, 1.0, 0.0], device=self.device)
                    paths_emb[p_sel, l_sel, D-3:D] = onehot
                return {
                    'paths_emb': paths_emb,
                    'attn_mask': attn_mask,
                    'node_ids': node_ids,
                    'file': file_path,
                    'anchor_p': torch.tensor(p_sel, dtype=torch.long, device=self.device),
                    'anchor_l': torch.tensor(l_sel, dtype=torch.long, device=self.device),
                    'anchor_v': torch.tensor(v_sel, dtype=torch.long, device=self.device),
                }
            else:
                return {
                    'paths_emb': paths_emb,
                    'attn_mask': attn_mask,
                    'node_ids': node_ids,
                    'file': file_path,
                }

        entry = self.data[idx]
        
        # Extract data from entry
        file_path = entry['file']
        info = entry['info']
        
        # Check if this is a new-format dataset with embeddings
        has_embeddings = 'struct_emb' in entry and 'gate_mapping' in entry
        
        if has_embeddings:
            struct_emb = entry['struct_emb']  # [N, D] embeddings for all nodes
            gate_mapping = entry['gate_mapping']  # original_id -> aig_id
        else:
            # Old format without embeddings - generate dummy embeddings
            struct_emb = None
            gate_mapping = {}
        
        # Get the paths (list of lists of node IDs)
        paths = info['paths']  # [[node_id, ...], [node_id, ...]]
        P = len(paths)
        
        # Determine embedding dimension
        if has_embeddings and struct_emb is not None:
            D = struct_emb.shape[1] if len(struct_emb.shape) > 1 else struct_emb.shape[0]
        else:
            D = 128  # Default embedding dimension
        
        # Add 3 dimensions for one-hot logic value (0, 1, X) if enabled
        if self.add_logic_value:
            D_total = D + 3
        else:
            D_total = D
        
        # Find max path length in this sample
        max_len = max(len(path) for path in paths)
        L = min(max_len, self.max_path_length)
        
        # Initialize tensors
        paths_emb = torch.zeros(P, L, D_total, dtype=torch.float32, device=self.device)
        attn_mask = torch.zeros(P, L, dtype=torch.bool, device=self.device)
        node_ids = torch.zeros(P, L, dtype=torch.long, device=self.device)
        
        # Fill in the data for each path
        for p, path in enumerate(paths):
            path_len = min(len(path), L)
            
            for pos in range(path_len):
                node_id = path[pos]
                node_ids[p, pos] = node_id
                attn_mask[p, pos] = True
                
                # Get base structural embedding
                base_embedding = None
                if has_embeddings and struct_emb is not None:
                    # Map original node ID to AIG node ID to get embedding
                    # Note: gate_mapping has string keys/values, but node_id is int
                    node_id_str = str(node_id)
                    if node_id_str in gate_mapping:
                        aig_id_str = gate_mapping[node_id_str]
                        aig_id = int(aig_id_str)  # Convert string to int for indexing
                        
                        # Get embedding for this AIG node
                        if aig_id < struct_emb.shape[0]:
                            embedding = struct_emb[aig_id]
                            if isinstance(embedding, torch.Tensor):
                                base_embedding = embedding.to(self.device)
                            else:
                                base_embedding = torch.tensor(
                                    embedding, dtype=torch.float32, device=self.device
                                )
                    # else: node not in mapping, use zero embedding
                else:
                    # Old format: generate random dummy embeddings for consistency
                    base_embedding = torch.randn(D, dtype=torch.float32, device=self.device)
                
                # Handle case where base_embedding is None (node not mapped)
                if base_embedding is None:
                    base_embedding = torch.zeros(D, dtype=torch.float32, device=self.device)
                
                # Add logic value feature (one-hot encoded: [is_0, is_1, is_X])
                if self.add_logic_value:
                    # Initialize all nodes with X (unknown) state: [0, 0, 1]
                    logic_value_onehot = torch.tensor([0.0, 0.0, 1.0], dtype=torch.float32, device=self.device)
                    # Concatenate base embedding with logic value
                    paths_emb[p, pos] = torch.cat([base_embedding, logic_value_onehot])
                else:
                    paths_emb[p, pos] = base_embedding
        
        # Optionally integrate anchor hint at dataset level
        if self.anchor_in_dataset:
            p_sel, l_sel, v_sel = self._gen_anchor_for_sample(node_ids, attn_mask, file_path)
            if p_sel >= 0 and l_sel >= 0 and self.add_logic_value and paths_emb.shape[-1] >= 3:
                D = paths_emb.shape[-1]
                onehot = torch.tensor([1.0, 0.0, 0.0], device=self.device)
                if v_sel == 1:
                    onehot = torch.tensor([0.0, 1.0, 0.0], device=self.device)
                paths_emb[p_sel, l_sel, D-3:D] = onehot
            return {
                'paths_emb': paths_emb,
                'attn_mask': attn_mask,
                'node_ids': node_ids,
                'file': file_path,
                'anchor_p': torch.tensor(p_sel, dtype=torch.long, device=self.device),
                'anchor_l': torch.tensor(l_sel, dtype=torch.long, device=self.device),
                'anchor_v': torch.tensor(v_sel, dtype=torch.long, device=self.device),
            }
        else:
            return {
                'paths_emb': paths_emb,
                'attn_mask': attn_mask,
                'node_ids': node_ids,
                'file': file_path,
            }

    # ------------------------------
    # Processed shard helpers
    # ------------------------------
    def _locate_shard(self, global_idx: int) -> Tuple[int, int]:
        acc = 0
        for i, sz in enumerate(self._shard_sizes):
            if global_idx < acc + sz:
                return i, global_idx - acc
            acc += sz
        raise IndexError(global_idx)

    def _ensure_shard_loaded(self, shard_id: int) -> None:
        if self._current_shard_id == shard_id and self._current_shard is not None:
            return
        # Free previous shard
        self._current_shard = None
        self._current_shard_id = None
        # Load new shard
        shard_path = self._shard_files[shard_id]
        shard = torch.load(shard_path, map_location='cpu')
        # Keep tensors on CPU; move to device in __getitem__ for the selected sample
        self._current_shard = shard
        self._current_shard_id = shard_id

    @staticmethod
    def preprocess_to_shards(
        input_dataset_path: str,
        output_dir: str,
        max_path_length: int = 50,
        shard_size: int = 5000,
        dtype: torch.dtype = torch.float16,
        device: torch.device = torch.device('cpu'),
    ) -> None:
        """Precompute per-sample tensors and save to shard files for fast training.

        This will read the pickle dataset (with struct_emb + gate_mapping), build
        paths_emb/attn_mask/node_ids for each sample (padded to max_path_length),
        and write them in shards to output_dir as shard_XXXXX.pt files.
        """
        os.makedirs(output_dir, exist_ok=True)

        # Use the same mapping logic via a temporary dataset instance (raw mode)
        raw_ds = ReconvergentPathsDataset(
            input_dataset_path,
            device=device,
            max_path_length=max_path_length,
            load_processed=False,
        )

        total = len(raw_ds)
        shard_idx = 0
        buf_paths: List[torch.Tensor] = []
        buf_masks: List[torch.Tensor] = []
        buf_nodes: List[torch.Tensor] = []
        buf_files: List[str] = []

        def flush() -> None:
            nonlocal shard_idx, buf_paths, buf_masks, buf_nodes, buf_files
            if not buf_paths:
                return
            # Final safety: ensure equal shapes before stacking
            base_shape = buf_paths[0].shape
            for j, t in enumerate(buf_paths):
                if t.shape != base_shape:
                    raise RuntimeError(
                        f"Inconsistent sample shape within shard buffer: idx 0 {base_shape} vs idx {j} {t.shape}"
                    )
            paths_t = torch.stack(buf_paths, dim=0).to(dtype)
            masks_t = torch.stack(buf_masks, dim=0)
            nodes_t = torch.stack(buf_nodes, dim=0)
            shard = {
                'paths_emb': paths_t.cpu(),
                'attn_mask': masks_t.cpu(),
                'node_ids': nodes_t.cpu(),
                'files': list(buf_files),
            }
            out_path = os.path.join(output_dir, f'shard_{shard_idx:05d}.pt')
            torch.save(shard, out_path)
            print(f"Wrote {out_path} ({paths_t.shape[0]} samples)")
            shard_idx += 1
            buf_paths, buf_masks, buf_nodes, buf_files = [], [], [], []

        for i in range(total):
            item = raw_ds[i]
            pe = item['paths_emb'].to(torch.float32).cpu()
            am = item['attn_mask'].cpu()
            ni = item['node_ids'].cpu()
            # Pad to fixed max_path_length for consistent stacking
            Pdim, Lcur, Ddim = pe.shape
            Lfix = max_path_length
            if Lcur < Lfix:
                pe_pad = torch.zeros(Pdim, Lfix, Ddim, dtype=pe.dtype)
                pe_pad[:, :Lcur, :] = pe
                am_pad = torch.zeros(Pdim, Lfix, dtype=am.dtype)
                am_pad[:, :Lcur] = am
                ni_pad = torch.zeros(Pdim, Lfix, dtype=ni.dtype)
                ni_pad[:, :Lcur] = ni
                pe, am, ni = pe_pad, am_pad, ni_pad
            elif Lcur > Lfix:
                pe = pe[:, :Lfix, :]
                am = am[:, :Lfix]
                ni = ni[:, :Lfix]

            # Assert shapes are consistent now
            assert pe.shape[1] == max_path_length, f"pe length {pe.shape[1]} != {max_path_length}"
            assert am.shape[1] == max_path_length, f"am length {am.shape[1]} != {max_path_length}"
            assert ni.shape[1] == max_path_length, f"ni length {ni.shape[1]} != {max_path_length}"

            buf_paths.append(pe)
            buf_masks.append(am)
            buf_nodes.append(ni)
            buf_files.append(item['file'])
            if len(buf_paths) >= shard_size:
                flush()
        flush()
        print(f"Preprocessing complete. Shards saved to {output_dir}")


if __name__ == '__main__':
    # Minimal CLI to run preprocessing via `python -m src.ml.reconv_ds ...`
    import argparse

    parser = argparse.ArgumentParser(description='Preprocess reconvergent dataset to tensor shards')
    parser.add_argument('--input', dest='input_dataset_path', type=str, required=True,
                        help='Path to input pickle dataset (from reconv_podem)')
    parser.add_argument('--out', dest='output_dir', type=str, required=True,
                        help='Directory to write shard_XXXXX.pt files')
    parser.add_argument('--max_len', dest='max_path_length', type=int, default=50,
                        help='Fixed path length to pad/truncate to')
    parser.add_argument('--shard_size', dest='shard_size', type=int, default=5000,
                        help='Number of samples per shard file')
    parser.add_argument('--dtype', dest='dtype', type=str, default='float16', choices=['float16', 'float32'],
                        help='Data type for stored embeddings')

    args = parser.parse_args()
    dtype = torch.float16 if args.dtype == 'float16' else torch.float32

    ReconvergentPathsDataset.preprocess_to_shards(
        input_dataset_path=args.input_dataset_path,
        output_dir=args.output_dir,
        max_path_length=args.max_path_length,
        shard_size=args.shard_size,
        dtype=dtype,
        device=torch.device('cpu'),
    )


def reconv_collate(batch: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Collate variable-length samples into a batch.
    
    Parameters
    ----------
    batch : list[dict]
        List of samples from ReconvergentPathsDataset.
    
    Returns
    -------
    dict
        Batched dictionary with keys:
        - paths_emb: [B, P, L, D] batched path embeddings
        - attn_mask: [B, P, L] batched attention masks
        - node_ids: [B, P, L] batched node IDs
        - files: list[str] file paths for each sample in batch
    """
    if not batch:
        raise ValueError("Cannot collate empty batch")
    
    device = batch[0]['paths_emb'].device
    
    # Find maximum dimensions across the batch
    P = max(item['paths_emb'].size(0) for item in batch)
    L = max(item['paths_emb'].size(1) for item in batch)
    D_raw = batch[0]['paths_emb'].size(2)
    B = len(batch)
    
    # Pad embedding dimension to be divisible by 4 (common nhead value)
    # This ensures transformer compatibility
    nhead = 4
    if D_raw % nhead == 0:
        D = D_raw
    else:
        D = ((D_raw // nhead) + 1) * nhead
    
    # Initialize batch tensors with zeros/False
    paths = torch.zeros(B, P, L, D, device=device, dtype=torch.float32)
    masks = torch.zeros(B, P, L, dtype=torch.bool, device=device)
    node_ids = torch.zeros(B, P, L, dtype=torch.long, device=device)
    files: List[str] = []
    
    # Fill in data from each sample
    for b, item in enumerate(batch):
        p, l_i, d = item['paths_emb'].shape
        # Copy embeddings (padding happens automatically via zeros initialization)
        paths[b, :p, :l_i, :d] = item['paths_emb']
        masks[b, :p, :l_i] = item['attn_mask']
        node_ids[b, :p, :l_i] = item['node_ids']
        files.append(item['file'])
    
    out: Dict[str, Any] = {
        'paths_emb': paths,
        'attn_mask': masks,
        'node_ids': node_ids,
        'files': files,
    }
    # Collate optional anchors if present
    if 'anchor_p' in batch[0] and 'anchor_l' in batch[0] and 'anchor_v' in batch[0]:
        ap = torch.stack([item['anchor_p'] for item in batch], dim=0)
        al = torch.stack([item['anchor_l'] for item in batch], dim=0)
        av = torch.stack([item['anchor_v'] for item in batch], dim=0)
        out['anchor_p'] = ap
        out['anchor_l'] = al
        out['anchor_v'] = av
    return out
